import asyncio
import time
import random

import aiohttp
from aiohttp import ClientTimeout

URL_LIST = [
    "https://www.google.com",
    "https://www.facebook.com",
    "https://www.amazon.com",
    "https://www.imdb.com",
    "https://www.apple.com",
    "https://www.merriam-webster.com",
    "https://www.pinterest.com",
    "https://www.yelp.com",
    "https://www.tripadvisor.com",
    "https://www.wiktionary.org",
    "https://www.dictionary.com",
    "https://www.yahoo.com",
    "https://www.cambridge.org",
    "https://www.britannica.com",
    "https://www.weather.com",
    "https://www.microsoft.com",
    "https://www.walmart.com",
    "https://www.espn.com",
    "https://www.linkedin.com",
    "https://www.homedepot.com",
    "https://www.espncricinfo.com",
    "https://www.craigslist.org",
    "https://www.xnxx.com",
    "https://www.gsmarena.com",
    "https://www.mayoclinic.org",
    "https://www.cricbuzz.com",
    "https://www.timeanddate.com",
    "https://www.webmd.com",
    "https://www.thesaurus.com",
    "https://www.whatsapp.com",
    "https://www.rottentomatoes.com",
    "https://www.bbc.com",
    "https://www.bestbuy.com",
    "https://www.healthline.com",
    "https://www.netflix.com",
    "https://www.indeed.com",
    "https://www.thefreedictionary.com",
    "https://www.xvideos.com",
    "https://www.spotify.com",
    "https://www.livescore.com",
    "https://www.ebay.com",
    "https://www.pornhub.com",
    "https://www.ytmp3.cc",
    "https://www.samsung.com",
    "https://www.nih.gov",
    "https://www.tiktok.com",
    "https://www.steampowered.com",
    "https://www.investopedia.com",
    "https://www.cdc.gov",
    "https://www.nordstrom.com",
    "https://www.blog.google",
    "https://www.cnbc.com",
    "https://www.indiatimes.com",
    "https://www.roblox.com",
    "https://www.flashscore.com",
    "https://www.thepiratebay.org",
    "https://www.adobe.com",
    "https://www.cnn.com",
    "https://www.speedtest.net",
    "https://www.ssyoutube.com",
    "https://www.unsplash.com",
    "https://www.lowes.com",
    "https://www.vocabulary.com",
    "https://www.marketwatch.com",
    "https://www.mcdonalds.com",
    "https://www.deepl.com",
    "https://www.playstation.com",
    "https://www.bloomberg.com",
    "https://www.forbes.com",
    "https://www.livescore.in",
    "https://www.booking.com",
    "https://www.clevelandclinic.org",
    "https://www.xhamster.com",
    "https://www.xe.com",
    "https://www.friv.com",
    "https://www.coinmarketcap.com",
    "https://www.spanishdict.com",
    "https://www.goodhousekeeping.com",
    "https://www.instructure.com",
    "https://www.dominos.com",
    "https://www.wunderground.com",
    "https://www.yourdictionary.com",
    "https://www.cnet.com",
    "https://www.twitch.tv",
    "https://www.pexels.com",
    "https://www.poki.com",
    "https://www.caranddriver.com",
    "https://www.github.com",
    "https://www.hotels.com",
    "https://www.globo.com",
    "https://www.soundcloud.com",
    "https://www.theguardian.com",
    "https://www.usnews.com",
    "https://www.livescores.com",
    "https://www.wellsfargo.com",
    "https://www.parade.com",
    "https://www.expedia.com",
    "https://www.foxnews.com",
    "https://www.realtor.com",
    "https://www.crazygames.com",
    "https://www.detik.com",
    "https://www.welt.de",
    "https://www.taringa.net",
    "https://www.ea.com",
    "https://www.windows.net",
    "https://www.bloglovin.com",
    "https://www.imageshack.us",
    "https://www.disney.com",
    "https://www.cambridge.org",
    "https://www.cointernet.com.co",
    "https://www.urbandictionary.com",
    "https://www.eventbrite.com",
    "https://www.www.livejournal.com",
    "https://www.springer.com",
    "https://www.outlook.com",
    "https://www.wikihow.com",
    "https://www.stanford.edu",
    "https://www.nikkei.com",
    "https://www.rakuten.co.jp",
    "https://www.hindustantimes.com",
    "https://www.rtve.es",
    "https://www.prezi.com",
    "https://www.deezer.com",
    "https://www.id.wikipedia.org",
    "https://www.discord.gg",
    "https://www.yandex.ru",
    "https://www.search.yahoo.com",
    "https://www.amazon.fr",
    "https://www.yelp.com",
    "https://www.arxiv.org",
    "https://www.goodreads.com",
    "https://www.pbs.org",
    "https://www.alibaba.com",
    "https://www.hubspot.com",
    "https://www.rambler.ru",
    "https://www.plos.org",
    "https://www.www.wix.com",
    "https://www.google.pl",
    "https://www.aol.com",
    "https://www.fb.me",
    "https://www.twitch.tv",
    "https://www.gnu.org",
    "https://www.mega.nz",
    "https://www.francetvinfo.fr",
    "https://www.pinterest.fr",
    "https://www.ria.ru",
    "https://www.sakura.ne.jp",
    "https://www.guardian.co.uk",
    "https://www.000webhost.com",
    "https://www.cnil.fr",
    "https://www.android.com",
    "https://www.smh.com.au",
    "https://www.rt.com",
    "https://www.usnews.com",
    "https://www.nginx.org",
    "https://www.nbcnews.com",
    "https://www.google.nl",
    "https://www.dw.com",
    "https://www.canada.ca",
    "https://www.theatlantic.com",
    "https://www.google.ru",
    "https://www.liveinternet.ru",
    "https://www.engadget.com",
    "https://www.bp1.blogger.com",
    "https://www.lefigaro.fr",
    "https://www.timeweb.ru",
    "https://www.akamaized.net",
    "https://www.zdf.de",
    "https://www.addthis.com",
    "https://www.20minutos.es",
    "https://www.pexels.com",
    "https://www.mystrikingly.com",
    "https://www.cnbc.com",
    "https://www.picasa.google.com",
    "https://www.ipv4.google.com",
    "https://www.kickstarter.com",
    "https://www.elsevier.com",
    "https://www.godaddy.com",
    "https://www.themeforest.net",
    "https://www.addtoany.com",
    "https://www.abcnews.go.com",
    "https://www.cornell.edu",
    "https://www.wikia.com",
    "https://www.npr.org",
    "https://www.gofundme.com",
    "https://www.alicdn.com",
    "https://www.sciencedirect.com",
    "https://www.cpanel.com",
    "https://www.academia.edu",
    "https://www.gmail.com",
    "https://www.thetimes.co.uk",
    "https://www.unesco.org",
    "https://www.code.google.com",
    "https://www.surveymonkey.com",
    "https://www.amzn.to",
    "https://www.amazonaws.com",
    "https://www.nydailynews.com",
    "https://www.webnode.page",
    "https://www.sky.com",
    "https://www.whitehouse.gov",
    "https://www.ovhcloud.com",
    "https://www.psychologytoday.com",
    "https://www.yahoo.co.jp",
    "https://www.netflix.com",
    "https://www.it.wikipedia.org",
    "https://www.ibm.com",
    "https://www.ft.com",
    "https://www.www.gov.br",
    "https://www.britannica.com",
    "https://www.espn.com",
    "https://www.statista.com",
    "https://www.alexa.com",
    "https://www.newyorker.com",
    "https://www.sendspace.com",
    "https://www.abc.es",
    "https://www.buzzfeed.com",
    "https://www.www.wikipedia.org",
    "https://www.gooyaabitemplates.com",
    "https://www.mit.edu",
    "https://www.techcrunch.com",
    "https://www.newsweek.com",
    "https://www.ovh.net",
    "https://www.sputniknews.com",
    "https://www.zoom.us",
    "https://www.apache.org",
    "https://www.economist.com",
    "https://www.insider.com",
    "https://www.sfgate.com",
    "https://www.unsplash.com",
    "https://www.tripadvisor.com",
    "https://www.oracle.com",
    "https://www.wired.com",
    "https://www.home.pl",
    "https://www.quora.com",
    "https://www.photos1.blogger.com",
    "https://www.gizmodo.com",
    "https://www.ca.gov",
    "https://www.weibo.com",
    "https://www.huawei.com",
    "https://www.php.net",
    "https://www.loc.gov",
    "https://www.hp.com",
    "https://www.vice.com",
    "https://www.target.com",
    "https://www.ietf.org",
    "https://www.disqus.com",
    "https://www.nicovideo.jp",
    "https://www.amazon.es",
    "https://www.redbull.com",
    "https://www.naver.com",
    "https://www.oup.com",
    "https://www.latimes.com",
    "https://www.steampowered.com",
    "https://www.tmz.com",
    "https://www.akamaihd.net",
    "https://www.nypost.com",
    "https://www.sciencedaily.com",
    "https://www.instructables.com",
    "https://www.washington.edu",
    "https://www.freepik.com",
    "https://www.zendesk.com",
    "https://www.thenai.org",
    "https://www.zippyshare.com",
    "https://www.ouest-france.fr",
    "https://www.sapo.pt",
    "https://www.wiley.com",
    "https://www.mozilla.com",
    "https://www.nationalgeographic.com",
    "https://www.berkeley.edu",
    "https://www.ftc.gov",
    "https://www.spiegel.de",
    "https://www.groups.google.com",
    "https://www.nginx.com",
    "https://www.sedo.com",
    "https://www.ziddu.com",
    "https://www.rapidshare.com",
    "https://www.ovh.com",
    "https://www.icann.org",
    "https://www.e-monsite.com",
    "https://www.harvard.edu",
    "https://www.finance.yahoo.com",
    "https://www.googleblog.com",
    "https://www.marca.com",
    "https://www.biglobe.ne.jp",
    "https://www.dropcatch.com",
    "https://www.mashable.com",
    "https://www.lavanguardia.com",
    "https://www.doi.org",
    "https://www.m.wikipedia.org",
    "https://www.yandex.com",
    "https://www.hollywoodreporter.com",
    "https://www.theverge.com",
    "https://www.variety.com",
    "https://www.clickbank.net",
    "https://www.about.com",
    "https://www.bandcamp.com",
    "https://www.ssl-images-amazon.com",
    "https://www.linktr.ee",
    "https://www.elmundo.es",
    "https://www.bp2.blogger.com",
    "https://www.calendar.google.com",
    "https://www.playstation.com",
    "https://www.cbc.ca",
    "https://www.walmart.com",
    "https://www.clarin.com",
    "https://www.abc.net.au",
    "https://www.netlify.app",
    "https://www.dreamstime.com",
    "https://www.www.over-blog.com",
    "https://www.reg.ru",
    "https://www.yadi.sk",
    "https://www.google.ca",
    "https://www.ted.com",
    "https://www.softonic.com",
    "https://www.kakao.com",
    "https://www.google.com.tw",
    "https://www.upenn.edu",
    "https://www.jhu.edu",
    "https://www.ign.com",
    "https://www.boston.com",
    "https://www.apnews.com",
    "https://www.nba.com",
    "https://www.seesaa.net",
    "https://www.salesforce.com",
    "https://www.itmedia.co.jp",
    "https://www.scmp.com",
    "https://www.focus.de",
    "https://www.canva.com",
    "https://www.video.google.com",
    "https://www.marthastewart.com",
    "https://www.euronews.com",
    "https://www.trustpilot.com",
    "https://www.weather.com",
    "https://www.etsy.com",
    "https://www.gettyimages.com",
    "https://www.google.co.id",
    "https://www.m.me",
    "https://www.g.co",
    "https://www.dictionary.com",
    "https://www.justjared.com",
    "https://www.usgs.gov",
    "https://www.nokia.com",
    "https://www.reddit.com",
    "https://www.twimg.com",
    "https://www.bustle.com",
    "https://www.stackoverflow.com",
    "https://www.amazon.ca",
    "https://www.messenger.com",
    "https://www.last.fm",
    "https://www.sina.com.cn",
    "https://www.sec.gov",
    "https://www.google.co.th",
    "https://www.utexas.edu",
    "https://www.fifa.com",
    "https://www.ucla.edu",
    "https://www.flickr.com",
    "https://www.unicef.org",
    "https://www.goo.ne.jp",
    "https://www.umn.edu",
    "https://www.biblegateway.com",
    "https://www.radiofrance.fr",
    "https://www.repubblica.it",
    "https://www.venturebeat.com",
    "https://www.box.com",
    "https://www.ap.org",
    "https://www.depositfiles.com",
    "https://www.news.com.au",
    "https://www.blog.google",
    "https://www.kompas.com",
    "https://www.evernote.com",
    "https://www.secureserver.net",
    "https://www.soratemplates.com",
    "https://www.standard.co.uk",
    "https://www.getbootstrap.com",
    "https://www.nps.gov",
    "https://www.howstuffworks.com",
    "https://www.joomla.org",
    "https://www.admin.ch",
    "https://www.com.com",
    "https://www.people.com",
    "https://www.stores.jp",
    "https://www.nifty.com",
    "https://www.doubleclick.net",
    "https://www.nhk.or.jp",
    "https://www.lego.com",
    "https://www.jstor.org",
    "https://www.lg.com",
    "https://www.privacy.google.com",
    "https://www.usda.gov",
    "https://www.eonline.com",
    "https://www.uefa.com",
    "https://www.nvidia.com",
    "https://www.bp3.blogger.com",
    "https://www.princeton.edu",
    "https://www.ehow.com",
    "https://www.bigcommerce.com",
    "https://www.fda.gov",
    "https://www.example.com",
    "https://www.justgiving.com",
    "https://www.discogs.com",
    "https://www.prestashop.com",
    "https://www.politico.com",
    "https://www.bp0.blogger.com",
    "https://www.jpost.com",
    "https://www.pinterest.co.uk",
    "https://www.esa.int",
    "https://www.imageshack.com",
    "https://www.state.gov",
    "https://www.hm.com",
    "https://www.tvtropes.org",
    "https://www.mixcloud.com",
]


S_TIMES = []
s_errors = 0
O_TIMES = []
o_errors = 0

TIMEOUT = ClientTimeout(sock_read=1.0, sock_connect=1.0)


async def get(url):
    start_t = time.time()
    try:
        connector = aiohttp.TCPConnector(use_dns_cache=False)
        async with aiohttp.ClientSession(
            connector=connector, timeout=TIMEOUT
        ) as session:
            response = await session.get(url=url)
            _ = await response.read()
            await session.close()
    except:
        o_errors = +1
    O_TIMES.append(time.time() - start_t)


async def get_with_session(url, session):
    start_t = time.time()
    try:
        async with session.get(url=url) as response:
            _ = await response.read()
    except:
        s_errors = +1
    S_TIMES.append(time.time() - start_t)


async def main_with_session(url_list: list[str]):
    connector = aiohttp.TCPConnector(use_dns_cache=False)
    session = aiohttp.ClientSession(connector=connector, timeout=TIMEOUT)
    start_t = time.time()
    _ = await asyncio.gather(*[get_with_session(url, session) for url in url_list])
    print(
        f"main_with_session took {time.time() - start_t} millis. avg {sum(S_TIMES) / len(S_TIMES)}, {s_errors} errors"
    )
    await session.close()


async def main_with_open(url_list: list[str]):
    start_t = time.time()
    _ = await asyncio.gather(*[get(url) for url in url_list])
    print(
        f"main_with_open took {time.time() - start_t} millis. avg {sum(O_TIMES) / len(O_TIMES)}, {o_errors} errors"
    )


if __name__ == "__main__":
    for i in range(1, 5):
        random_100 = random.choices(URL_LIST, k=100)
        fn_list = [main_with_session(random_100), main_with_open(random_100)]
        random.shuffle(fn_list)
        print(f"run {i}:")
        for f in fn_list:
            asyncio.run(f)
